[project]
name = "Experience multiplier"
version = "1.0"
authors = [{ name = "youdietoo" }]
description = "Adds configurable experience multiplication.

Original by: plu5"

description = """\
"Adds configurable experience multiplication.

Original by: plu5"
"""

[tool.sdkmod]
name = "Experience multiplier"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
download = ""
version = "1"
